winget install --id=Microsoft.WindowsTerminal --accept-package-agreements --accept-source-agreements
winget install --id=Microsoft.VisualStudioCode --accept-package-agreements --accept-source-agreements
winget install --id=Microsoft.PowerToys --accept-package-agreements --accept-source-agreements
winget install --id=voidtools.Everything --accept-package-agreements --accept-source-agreements
winget install --id=WinDirStat.WinDirStat --accept-package-agreements --accept-source-agreements
winget install --id=Nilesoft.Shell --accept-package-agreements --accept-source-agreements
winget install --id=9PGCV4V3BK4W -s msstore --accept-package-agreements --accept-source-agreements
winget install --id=glzr-io.glazewm --accept-package-agreements --accept-source-agreements
winget install --id=JanDeDobbeleer.OhMyPosh -s winget --accept-package-agreements --accept-source-agreements
winget install --id=GitHub.GitHubDesktop --accept-package-agreements --accept-source-agreements
winget install --id=GitHub.cli --accept-package-agreements --accept-source-agreements
winget install --id=JetBrains.Toolbox --accept-package-agreements --accept-source-agreements
winget install --id=Spotify.Spotify --accept-package-agreements --accept-source-agreements
winget install --id=Discord.Discord --accept-package-agreements --accept-source-agreements
winget install --id=Valve.Steam --accept-package-agreements --accept-source-agreements